# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
#
# This file contains the workflows that are run periodically to build the examples.

name: build_esp32s3

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build_esp32s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Clone IDF
        run: |
          git clone --recursive --single-branch -b release/v4.4 https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh
          cd -
      - name: Build ESP32-S3
        run: |
          cd esp-idf
          . export.sh
          cd -
          export IDF_PATH=`pwd`/esp-idf
          echo "IDF_PATH is set to $IDF_PATH"
          ./scripts/build_examples.sh esp32s3
